# Generated by Django 3.0 on 2019-12-06 17:46

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('available_transportation', models.TextField()),
                ('parent_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.Location')),
            ],
        ),
        migrations.CreateModel(
            name='ProvidedService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TargetPopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('localizability', models.CharField(choices=[('FIX', 'Fixed'), ('MOB', 'Mobile'), ('VIR', 'Virtual/Cyber')], max_length=3)),
                ('url', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('hours_of_operation', models.TextField()),
                ('holiday_hours_of_operation', models.TextField()),
                ('child_friendly', models.BooleanField()),
                ('capacity', models.IntegerField()),
                ('internet_access', models.BooleanField()),
                ('wifi_network', models.CharField(max_length=100)),
                ('computers_available', models.BooleanField()),
                ('open_to_public', models.BooleanField()),
                ('sensitive', models.BooleanField()),
                ('date_entered', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('accessibility', models.ManyToManyField(to='assets.AccessibilityFeature')),
                ('asset_type', models.ManyToManyField(to='assets.AssetType')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.DataSource')),
                ('hard_to_count_population', models.ManyToManyField(to='assets.TargetPopulation')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.Location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.Organization')),
                ('services', models.ManyToManyField(to='assets.ProvidedService')),
            ],
        ),
    ]
