# Generated by Django 3.0 on 2019-12-12 17:37

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_location_geom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='accessibility',
            new_name='accessibility_features',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_type',
            new_name='asset_types',
        ),
        migrations.RemoveField(
            model_name='location',
            name='address',
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='street_address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='zip_code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='child_friendly',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='computers_available',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='date_entered',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='holiday_hours_of_operation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='hours_of_operation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='internet_access',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='localizability',
            field=models.CharField(choices=[('FIX', 'Fixed'), ('MOB', 'Mobile'), ('VIR', 'Cyber')], max_length=3),
        ),
        migrations.AlterField(
            model_name='asset',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='asset',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='wifi_network',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='available_transportation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Location'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
