# Generated by Django 3.0 on 2019-12-12 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20191212_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.DataSource'),
        ),
    ]
