# Generated by Django 3.0.4 on 2020-03-11 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20191212_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='do_not_display',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='etl_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='periodicity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='primary_key_from_rocket',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='parcel_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='residence',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='accessibility_features',
            field=models.ManyToManyField(blank=True, to='assets.AccessibilityFeature'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='hard_to_count_population',
            field=models.ManyToManyField(blank=True, to='assets.TargetPopulation'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='localizability',
            field=models.CharField(blank=True, choices=[('FIX', 'Fixed'), ('MOB', 'Mobile'), ('VIR', 'Cyber')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.Location'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='open_to_public',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.Organization'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='sensitive',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='services',
            field=models.ManyToManyField(blank=True, to='assets.ProvidedService'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='street_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(blank=True, to='assets.Tag'),
        ),
    ]
