# Generated by Django 3.0.4 on 2020-03-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20200311_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
