# Generated by Django 3.0.4 on 2020-03-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20200311_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
