# Generated by Django 3.0.4 on 2020-03-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20200311_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
