# Generated by Django 3.0.4 on 2020-05-28 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_auto_20200519_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='category',
        ),
    ]
