# Generated by Django 3.0.6 on 2020-05-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0011_auto_20200519_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('HEALTHCARE', 'Health care'), ('FOOD', 'Food assistance'), ('HOUSING', 'Housing assistance'), ('FINANCIAL', 'Financial assistance'), ('EMERGENCY_SUPPLIES', 'Emergency supplies')], max_length=50)),
                ('assets', models.ManyToManyField(related_name='resources', to='assets.Asset')),
                ('other_locations', models.ManyToManyField(related_name='resources', to='assets.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('resources', models.ManyToManyField(related_name='communities', to='community_resources.Resource')),
            ],
            options={
                'verbose_name_plural': 'Communities',
            },
        ),
    ]
