# Generated by Django 3.0.6 on 2020-05-19 21:36

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('community_resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='alert_content',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='community',
            name='top_section_content',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resource',
            name='recurrence',
            field=recurrence.fields.RecurrenceField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='community_resources.ResourceCategory'),
        ),
    ]
