# Generated by Django 3.0.6 on 2020-05-21 15:33

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20200521_1533'),
        ('community_resources', '0002_auto_20200519_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='resource',
            name='category',
        ),
        migrations.AddField(
            model_name='community',
            name='neighborhoods',
            field=models.ManyToManyField(to='geo.Neighborhood'),
        ),
        migrations.AddField(
            model_name='resource',
            name='categories',
            field=models.ManyToManyField(related_name='resources', to='community_resources.ResourceCategory'),
        ),
        migrations.AddField(
            model_name='resource',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='resource',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Top'), (1, 'High'), (2, 'Medium'), (3, 'Low')], default=2, help_text='This helps determine the order in which resources are listed.'),
        ),
        migrations.AddField(
            model_name='resource',
            name='published',
            field=models.BooleanField(default=False, help_text='When checked, activity will show up on the site.'),
        ),
        migrations.AddField(
            model_name='resource',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='After this date, the resource will show up on the site (default is today)'),
        ),
        migrations.AddField(
            model_name='resource',
            name='stop_date',
            field=models.DateField(blank=True, help_text='After this date, the resource will stop showing up on the site (leave blank to keep up indefinitely)', null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='populations_served',
            field=models.ManyToManyField(related_name='resources', to='community_resources.Population'),
        ),
        migrations.CreateModel(
            name='CategorySection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections_by_community', to='community_resources.ResourceCategory')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_sections', to='community_resources.Community')),
            ],
            options={
                'unique_together': {('community', 'category')},
            },
        ),
    ]
