# Generated by Django 3.0.4 on 2020-05-28 00:57

import ckeditor.fields
from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('community_resources', '0004_auto_20200527_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='population',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='resource',
            name='recurrence',
            field=recurrence.fields.RecurrenceField(blank=True, null=True),
        ),
    ]
