# Generated by Django 3.0.4 on 2020-05-28 12:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_resources', '0005_auto_20200528_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='population',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
