# Generated by Django 3.0.4 on 2020-05-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_resources', '0006_auto_20200528_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecategory',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
