# Generated by Django 3.0.4 on 2020-05-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_resources', '0007_resourcecategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcecategory',
            name='image',
            field=models.ImageField(null=True, upload_to='icons'),
        ),
    ]
