# Generated by Django 3.0.4 on 2020-06-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_resources', '0008_auto_20200529_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
