/*
 *
 * Global constants
 *
 */

export const GET_COMMUNITY_DATA_REQUEST =
  'app/Global/GET_COMMUNITY_DATA_REQUEST';
export const GET_COMMUNITY_DATA_SUCCESS =
  'app/Global/GET_COMMUNITY_DATA_SUCCESS';
export const GET_COMMUNITY_DATA_FAILURE =
  'app/Global/GET_COMMUNITY_DATA_FAILURE';

export const SEARCH_RESOURCE_REQUEST = 'app/Global/SEARCH_RESOURCE_REQUEST';
export const SEARCH_RESOURCE_SUCCESS = 'app/Global/SEARCH_RESOURCE_SUCCESS';
export const SEARCH_RESOURCE_FAILURE = 'app/Global/SEARCH_RESOURCE_FAILURE';
