# Generated by Django 2.2 on 2019-09-06 19:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('geo_level', models.CharField(blank=True, choices=[('NONE', 'N/A'), ('BLOCKGROUP', 'Block group'), ('TRACT', 'Tract'), ('COUNTY_SUBDIVISION', 'County Subdivision'), ('COUNTY', 'County'), ('PLACE', 'Place'), ('PUMA', 'PUMA'), ('STATE_HOUSE', 'State House'), ('STATE_SENATE', 'State Senate'), ('SCHOOL_DISTRICT', 'School District')], default='NONE', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CensusGeography',
            fields=[
                ('geography_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geo.Geography')),
                ('affgeoid', models.CharField(max_length=21, unique=True)),
                ('lsad', models.CharField(max_length=2)),
                ('aland', models.BigIntegerField(verbose_name='Area (land)')),
                ('awater', models.BigIntegerField(verbose_name='Area (water)')),
            ],
            bases=('geo.geography',),
        ),
        migrations.CreateModel(
            name='BlockGroup',
            fields=[
                ('censusgeography_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='geo.CensusGeography')),
                ('geoid', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('statefp', models.CharField(max_length=2)),
                ('countyfp', models.CharField(max_length=3)),
                ('tractce', models.CharField(max_length=6)),
                ('blkgrpce', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Block Groups',
            },
            bases=('geo.censusgeography',),
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('censusgeography_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='geo.CensusGeography')),
                ('geoid', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('statefp', models.CharField(max_length=2)),
                ('countyfp', models.CharField(max_length=5)),
                ('countyns', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Counties',
            },
            bases=('geo.censusgeography',),
        ),
        migrations.CreateModel(
            name='CountySubdivision',
            fields=[
                ('censusgeography_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='geo.CensusGeography')),
                ('geoid', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('statefp', models.CharField(max_length=2)),
                ('countyfp', models.CharField(max_length=3)),
                ('cousubfp', models.CharField(max_length=5)),
                ('cousubns', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'County Subdivisions',
            },
            bases=('geo.censusgeography',),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('censusgeography_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='geo.CensusGeography')),
                ('geoid', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('statefp', models.CharField(max_length=2)),
                ('placefp', models.CharField(max_length=5)),
                ('placens', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Places',
            },
            bases=('geo.censusgeography',),
        ),
        migrations.CreateModel(
            name='Puma',
            fields=[
                ('censusgeography_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='geo.CensusGeography')),
                ('geoid', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('statefp', models.CharField(max_length=2)),
                ('pumace', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'PUMA',
                'verbose_name_plural': 'PUMAS',
            },
            bases=('geo.censusgeography',),
        ),
        migrations.CreateModel(
            name='SchoolDistrict',
            fields=[
                ('censusgeography_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='geo.CensusGeography')),
                ('geoid', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('statefp', models.CharField(max_length=2)),
                ('unsdlea', models.CharField(max_length=5)),
                ('placens', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'School Districts',
            },
            bases=('geo.censusgeography',),
        ),
        migrations.CreateModel(
            name='StateHouse',
            fields=[
                ('censusgeography_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='geo.CensusGeography')),
                ('geoid', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('statefp', models.CharField(max_length=2)),
                ('sldlst', models.CharField(max_length=5)),
                ('lsy', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'State House District',
                'verbose_name_plural': 'State House Districts',
            },
            bases=('geo.censusgeography',),
        ),
        migrations.CreateModel(
            name='StateSenate',
            fields=[
                ('censusgeography_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='geo.CensusGeography')),
                ('geoid', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('statefp', models.CharField(max_length=2)),
                ('sldust', models.CharField(max_length=5)),
                ('lsy', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'State Senate District',
                'verbose_name_plural': 'State Senate Districts',
            },
            bases=('geo.censusgeography',),
        ),
        migrations.CreateModel(
            name='Tract',
            fields=[
                ('censusgeography_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='geo.CensusGeography')),
                ('geoid', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('statefp', models.CharField(max_length=2)),
                ('countyfp', models.CharField(max_length=3)),
                ('tractce', models.CharField(max_length=6)),
            ],
            options={
                'verbose_name_plural': 'Tracts',
            },
            bases=('geo.censusgeography',),
        ),
    ]
