# Generated by Django 3.0.6 on 2020-05-21 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalGeography',
            fields=[
                ('geography_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geo.Geography')),
            ],
            bases=('geo.geography',),
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('geography_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geo.Geography')),
            ],
            bases=('geo.geography',),
        ),
        migrations.RemoveField(
            model_name='geography',
            name='geo_level',
        ),
    ]
